### ISSUE TITLE
Fixed curved polygons reading for Ron Lindout

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/aaime#23]
See https://osgeo-org.atlassian.net/browse/GEOT-5438 it contains full spec of the problem and a data sample.

**Comment by simboss** [comment]
I am assignin this to @fernandor777

**Comment by fernandor777** [comment]
PR sent:
https://github.com/geotools/geotools/pull/2115

**Comment by simboss** [comment]
@aaime can you review when you have some time

**Comment by simboss** [comment]
@fernandor777 this has been merged already

**Comment by fernandor777** [comment]
Needs 20.x backport since is a bug.
@simboss  should I do 19.x backport?

**Comment by simboss** [comment]
yeah, go ahead.

Fixes should go by default on all live branches.

**Comment by mbarto** [comment]
Backports for 20.x and 19.x have been merged

**Comment by simboss** [comment]
thx @mbarto

**Comment by simboss** [comment]
I will ask @aaime or @fernandor777 to test this on Mon
