### ISSUE TITLE
Estimate for GEOS-8890

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#34]
The JIRA issue is [this one](https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-8890).

**Comment by aaime** [comment]
Looked at it, the shapefile is "garbage" and uses chars that cannot be represented no matter how I look at them (whatever way I try to look at the files I end up getting the [replacement char], which then gets encoded verbatim, again, tried variations of the XStream XML driver, no dice.

I believe the issue starts with the sample file, which is clearly a GeoServer GetFeature WFS output (in shape-zip) format. Asked for the actual original data to look into it.

[replacement char]: https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character

**Comment by aaime** [comment]
Corti decided to sanitize the shapefiles in advance of uploading them, as he needs them to be used in WFS as well
