### ISSUE TITLE
Implement Curve Support for SQL Server

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#45]
See mailing list thread "Curve support for SQL Server"

**Comment by aaime** [comment]
Based on the following:
- Partial work done by Mark Prins on the topic (which has been shared publicly on the ml)
https://github.com/mprins/geotools/commit/e43286e7bae7101af0dad4edbee40f99ca81d4eb
- Previous parallel experience, adding support for curves in PostGIS for city of Helsinki, used 28 hours
- There is a binary format specification at https://docs.microsoft.com/en-us/openspecs/sql_server_protocols/ms-ssclrt/77460aa9-8c2f-4449-a65e-1d649ebd77fa 

I'd say that doing the work from scratch would take 4 days, but we have a head start from Mark Prins (which was not contributed btw, we'd have to check if we can use it). I'd say 4 if we have to start from scratch, 3 if we can use Mark's code.

**Comment by aaime** [comment]
Btw, we got a ping from the sponsor of this activity, shall we un-block this one?

**Comment by simboss** [comment]
We need to send a proposal and they need to sign it. 

I don't think we can unblock this.

**Comment by simboss** [comment]
Proposal is in, this is workable.

The client is asking us to backport to 2.16.
