### ISSUE TITLE
Discussion on performance and load tests for DG

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#51]
We should start a discussion with Daniele about creating (or revamping, not sure) a performance and load tests to run periodically which would evaluate performance of DG services.

The idea is to find performance degradations and bottlenecks as soon as possible rather than when we are in PROD.

Is this going to be an easy task, I don't think so but let's get started. Let's make proper care and defining also what we do need in terms of access to infrastructure and data to put this in place in an effective way.

**Comment by aaime** [comment]
https://docs.google.com/document/d/1UcDvPZudEm8IgRHYLvy1fvjHX-dJw1H60qbC9CTZxe0/edit
