### ISSUE TITLE
Review questions and styles from Vaisala

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#59]
As per our latest email exchange we need to review the provided styles and answer the open questions they have.

We need to make sure our estimate are enough to support these styles.

**Comment by aaime** [comment]
Checked the styles, there are a couple of differences:
* They use HSL/HSLA functions (official OTM styles use mostly rgb/rgba, there are examples of hsql but very few, did not notice them at first, found them now that I knew to look for them)
* They have word wrapping configs that are not supported by the current code

I've added a day and a half to the estimate to account for that.

**Comment by simboss** [comment]
I asked the client for an additional 1.5D and he agreed.

CLosing this down for now.
