### ISSUE TITLE
Estimates for new EUMETSAT work

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#61]

**Comment by aaime** [comment]
Note:

Access requirements: tutti/licenza. Su alcuni layer accesso a dato vedo tutti i tempi, se non autenticato solo tempi fino a 3 ore fa. (GeoFence, filtro sul tempo?).
Verificare che la cache funzioni nei due casi con client web su WMTS multidim e 

Importer: limitare le importazioni.
Ingestioni: round robin? Allora stato condiviso in cluster. E/O rimuovere global lock per importer?
