### ISSUE TITLE
Review of the draft specification on INSPIRE download services based on OGC API- Features

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/aaime#78]
Mail sent by ``Michael.LUTZ@ec.europa.eu`` the 05-12-2019 with header:
```
[FOR FEEDBACK] Draft specification on INSPIRE download services based on OGC API- Features
``` 

Copy pasting for reference:

> Dear colleagues,
>
> as you may know, as part of the INSPIRE MIG-T work on "Spatial data on the Web", we have been working on a draft specification for how to set up INSPIRE-compliant download services based on the OGC API - Features standard. There has been considerable interest in the INSPIRE community to use a modern standard based on Web principles for exposing spatial data under INSPIRE.
>
> One of the  main principles for this work has been to avoid INSPIRE-specific extensions and jargon as much as possible, to allow implementers to use off-the-shelf software directly. This is why we would like to receive feedback early-on from solution providers that have already implemented the standard.
>
> Please have a look at the draft specification and provide us with feedback on whether it is implementable  and easily supported by your OAPIF solution. Please use the GitHub issue tracker to provide your feedback or any errors or suggestions for improvement you may have.
>
> Please also consider the open questions in the document, for which we have already created issues in GitHub.
>
> We would appreciate to receive your feedback by 10 January 2020.
>
> Thanks & best regards,
> Heidi, Jari, Alex and Michael

Relevant links:
- https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md

**Comment by aaime** [comment]
The requirement to publish a single collection in a single dataset is problematic. In GeoServer we have dataset == workspace and collection is the layer, so one would have to publish one workspace per layer. This prevents making usage of a few current and future potential functionalities, such as the ability to download multiple layers in a single request (e.g., building a geopackage), performing joins, cross layer filtering and the like, that would normally be made available at the single service level (single dataset).

**Comment by aaime** [comment]
The requirement for an enclosure link seems problematic, the standard does not require it, the original dataset might not be feasible to download in a single shot... we could implement it though.
The enclosure should also be based on collections, not on datasets.

**Comment by aaime** [comment]
There are requirements on how to encode GeoJSON which are not a match for the current comlpex GeoJSON encoder (but not completely different either). See https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/geojson-encoding-rule.md

**Comment by aaime** [comment]
Also noticed lack of metadata links, as discussed in https://github.com/INSPIRE-MIF/gp-ogc-api-features/issues/23
