### ISSUE TITLE
Investigate GetFeatureInfo no returning on MetOp Layer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#8]
The layer is configured with a 48px buffer already, but no joy.

**Comment by simboss** [comment]
I mean, [this](http://pf-docker2.eoss-cloud.it/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng8&TRANSPARENT=true&QUERY_LAYERS=eumetsat%3Ametopa_ascat&LAYERS=eumetsat%3Ametopa_ascat&STYLES=&tiled=true&access_token=1a02e2e0-03ed-3426-a3f6-229b516a9126&TIME=2018-02-14T23%3A27%3A00.000Z&INFO_FORMAT=application%2Fjson&I=448&J=308&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=8.4375%2C157.5%2C9.140625%2C158.203125) does not return although being close to the point but [this](http://pf-docker2.eoss-cloud.it/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng8&TRANSPARENT=true&QUERY_LAYERS=eumetsat%3Ametopa_ascat&LAYERS=eumetsat%3Ametopa_ascat&STYLES=&tiled=true&access_token=1a02e2e0-03ed-3426-a3f6-229b516a9126&TIME=2018-02-14T23%3A27%3A00.000Z&INFO_FORMAT=application%2Fjson&I=448&J=308&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=8.4375%2C157.5%2C9.140625%2C158.203125&buffer=200) should return.

Am I missing something?

**Comment by aaime** [comment]
Is this the same as the wind arrow issue for Eumetsat?
