### ISSUE TITLE
Brain dump on TB16 activities

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/aaime#81]
- [ ] [D118 GeoPackage Server](https://docs.google.com/document/d/1sXD91a0Xnc3IgjArh79sfo48UvV16xJun6-ZVw8k0zU/edit)
- [ ] [D137 DGGS Server Implementation](https://docs.google.com/document/d/10x6tnsJCWarbOeSFDwNyE21EHgvEQwqxRHVfsoT7CTs/edit)
- [ ] [D138 DGGS Demo Client](https://docs.google.com/document/d/10qmpsDDCYknBvBiAxsxoySJYk9a4a3fNdaEy8Oj5xGU/edit)
- [ ] [D139 DGGS Enabled Data Services](https://docs.google.com/document/d/1ByF0BuEJ7_bjonw7fWYGQJjYk_Q-nyAsYnVLcQhCiao/edit)

**Comment by simboss** [comment]
this is closed right?

**Comment by aaime** [comment]
Well I did the first draft, there might be further discussion on it.

**Comment by simboss** [comment]
brain dump is done then, let's close it
