### ISSUE TITLE
List possible updates for GSR

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/aaime#83]
* Improvements for existing services
* GUI/HTML
* Image service
* Processing?

**Comment by simboss** [comment]
@aaime do you have a spreadsheet for this?

**Comment by simboss** [comment]
[here](https://docs.google.com/spreadsheets/d/1fd7UUXAYENs8vvr_0eqOJoXitPtXfOpXMo176I8jZrA/edit#gid=376642658) you go

**Comment by aaime** [comment]
I've updated the sheet with a number of new estimates:
https://docs.google.com/spreadsheets/d/1fd7UUXAYENs8vvr_0eqOJoXitPtXfOpXMo176I8jZrA/edit#gid=376642658

You can find them in the "Estimates new - NO HTML" tab, meaning, they estimate the raw REST service, without a HTML implementation of the resource, just JSON. Adding a HTML for each should be estimated on the side, some pages are a trivial static clone of the JSON, others are more complex forms.
Most estimates are "guessed", there are too many endpoints and the documentation is often lacking. Take them as ballpark, if you have to communicate to the client I'd suggest padding them, once we know what they actually want us to implement, we can spend some time playing with the service to figure out the undocumented bits.
